# Lista dos mercados dos principais mercados de acoes
markets = ["New York Stock Exchange",
           "NASDAQ",
           "Tokyo Stock Exchange",
           "Shanghai Stock Exchange",
           "Hong Kong Stock Exchange", 
           "Euronext",
           "London Stock Exchange Group",
           "Shenzhen Stock Exchange"]

# Lista de acoes de cada mercado
companies = {"New York Stock Exchange" : ["BABA", "V", "JNJ", "XOM", "WMT", "PG",
                                        "MA", "BAC", "DIS", "PFE", "T", "VZ",
                                        "UNH", "CVX", "KO", "HD", "MRK", "WFC",
                                        "NVS", "TSM"],
             "NASDAQ" : ["MSFT", "AMZN", "AAPL", "GOOGL", "GOOG", "FB", "CSCO",
                       "INTC", "CMCSA", "PEP", "NFLX", "ADBE", "PYPL", "COST",
                       "AVGO", "AMGN", "TXN", "SBUX", "NVDA", "CHTR"],
              "Tokyo Stock Exchange" : ["TOYOTA MOTOR CORPORATION","NTT DOCOMO,INC.",
              							"KDDI CORPORATION","HONDA MOTOR CO.,LTD.",
              							"JAPAN TOBACCO INC.","CANON INC","SONY CORPORATION",
              							"NISSAN MOTOR CO.,LTD.","Nintendo Co.,Ltd.",
              							"BRIDGESTONE CORPORATION","DAIKIN INDUSTRIES,LTD.",
              							"ASAHI INTECC CO.,LTD.","NIPPON SEIKI CO.,LTD.",
              							"McDonald's Holdings Company(Japan),Ltd.","FUKUDA DENSHI CO.,LTD.",
              							"TOEI ANIMATION CO.,LTD.","Hitachi,Ltd.","KOMATSU LTD.",
              							"ORIENTAL LAND CO.,LTD.","NIPPON STEEL & SUMITOMO METAL CORPORATION"],
              "Shanghai Stock Exchange" : ["SPD BANK", "DFAC", "CWTC","BEIJING CAPITAL",
                                           "SIA","BSU","HPI","Anhui Expressway","HUAXIA BANK",
                                           "CMBC","RIZHAO PORT","SIPG","Baosteel","Zhongyuan Expressway",
                                           "SEP", "SHANDONG STEEL","Zhejiang Energy Electric Power",
                                           "Huaneng Hydropower ", "CSET","HDPI"],
              "Hong Kong Stock Exchange" : ["CK Hutchison Holdings Limited","CLP Holdings Limited",
              								"The Hong Kong and China Gas Company Limited","The Wharf (Holdings) Limited",
              								" HSBC Holdings plc","Power Assets Holdings Limited",
              								"Hong Kong Finance Investment Holding Group Limited","PCCW Limited",
              								"Nine Express Limited","Hang Lung Group","Hang Seng Bank Ltd.",
              								"Henderson Land Development Co. Ltd.","Hysan Development Co. Ltd.",
              								"Vantage International (Holdings) Ltd.","Sun Hung Kai Properties Ltd.",
              								"New World Development Co., Ltd.","Oriental Press",
              								"Wheelock","Mexan","Glencore"],
              "Euronext" : ["ALMIL","2CRSI","MLATV","ASP","AALB,","ABI","AB","DOY","ABCA","ABEO","ABVX",
                            "ABN","ABO","MLGAI","GALIM","OR","LFVE","LBON","MLPGO","PSH","ZENT"],
              "London Stock Exchange Group" : ["MERL","CLG","NOG","MGP","CARR",
                                               "INDV","STOB","IAG","EZJ","SNR",
                                              "COST","IPF","NANO","ALFA","PAY",
                                               "KIE","MPO","FCH","PFC","TPT"],
              "Shenzhen Stock Exchange" : ["NHU","JSQH","WEIXING","HUAPONT PHARM","ETI","JINGGONG SCIENCE",
                                           "HUALAN BIO.","HAN'S LASER","MIRACLE LOGISTICS","KAN",
                                           "HAPM","NOVEL","XIAKE","SRZY","ZOJE","KHB","HAITE",
                                           "SUPOR","LIJIANG TOURISM"]
              }
